---
- name: Crating state
  block:
  - name: Creating state
    uri:
      url: "https://{{ domain_name }}/api/data/v1/location/create"
      method: POST
      headers:
        x-authenticated-user-token: "{{ keycloak_access_token }}"
        Authorization: "Bearer {{ core_vault_sunbird_api_auth_token }}"
      body_format: json
      body: |-
        {
          "request": {{ location_data.state }}
        }
    register: state_output
  - set_fact:
      state_id: "{{ state_output.json.result.id }}"

- name: Crating District
  block:
  - name: Crating District
    uri:
      url: "https://{{ domain_name }}/api/data/v1/location/create"
      method: POST
      headers:
        x-authenticated-user-token: "{{ keycloak_access_token }}"
        Authorization: "Bearer {{ core_vault_sunbird_api_auth_token }}"
      body_format: json
      body: |-
        {
          "request": {{ location_data.district }}
        }
    register: district_output
  - set_fact:
      district_id: "{{ district_output.json.result.id }}"

- name: Crating block
  block:
  - name: Crating block
    uri:
      url: "https://{{ domain_name }}/api/data/v1/location/create"
      method: POST
      headers:
        x-authenticated-user-token: "{{ keycloak_access_token }}"
        Authorization: "Bearer {{ core_vault_sunbird_api_auth_token }}"
      body_format: json
      body: |-
        {
          "request": {{ location_data.block }}
        }
    register: block_output
  - set_fact:
      block_id: "{{ block_output.json.result.id }}"

- name: Crating cluster
  block:
  - name: Crating cluster
    uri:
      url: "https://{{ domain_name }}/api/data/v1/location/create"
      method: POST
      headers:
        x-authenticated-user-token: "{{ keycloak_access_token }}"
        Authorization: "Bearer {{ core_vault_sunbird_api_auth_token }}"
      body_format: json
      body: |-
        {
          "request": {{ location_data.cluster }}
        }
    register: cluster_output
  - set_fact:
      cluster_id: "{{ cluster_output.json.result.id }}"




