---



- name: Assigning roles to user
  uri:
    url: "https://{{ domain_name }}/api/user/v2/role/assign"
    method: POST
    headers:
      Authorization: "Bearer {{ core_vault_sunbird_api_auth_token }}"
      x-authenticated-user-token: "{{ keycloak_access_token }}"
    body_format: json
    body: |-
     {
        "request": {
          "userId": "04dffd92-d478-4848-ac96-16314e64aa7a",
          "roles": [
            {
              "role": "ORG_ADMIN",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "REPORT_ADMIN",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "CONTENT_REVIEWER",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "COURSE_MENTOR",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "PUBLIC",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "ORG_MANAGEMENT",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "CONTENT_CREATOR",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "CONTENT_CURATION",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "SYSTEM_ADMINISTRATION", 
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "PROGRAM_MANAGER",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "REPORT_VIEWER",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "FLAG_REVIEWER",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "MEMBERSHIP_MANAGEMENT",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "BOOK_CREATOR",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            },
            {
              "role": "BOOK_REVIEWER",
              "operation":"add",
              "scope": [{ "organisationId": "{{ sunbird_custodian_org_id }}" }]
            }]
      }
     }
  


